local ts = require 'nvim-treesitter.configs'
ts.setup {
    ensure_installed = {
        'python',
        'go',
        'gomod',
        'gowork',
        'gosum',
        'groovy',
        'c',
        'cpp',
        'sql',
        'javascript',
        'typescript',
        'rust',
        'java',
        'json',
        'yaml',
        'vim',
        'vimdoc',
        'lua',
        'query',
        'comment',
    },
    highlight = { enable = true },
    indent = { enable = true },
}
