local wk = require("which-key")

wk.add({
    { "<S-Tab>", ":bn<CR>", desc = "next buffer" },
    { "<Tab>", "<C-^>", desc = "last buffer" },

    { "<leader> ", "<cmd>lua require('fzf-lua').buffers()<CR>", desc = "buffers" },
    { "<leader>/", "<cmd>lua require('fzf-lua').blines({start = 'cursor', fzf_cli_args = '--with-nth=3..'})<CR>", desc = "blines" },
    { "<leader>:", ":source ~/.local/share/nvim/sessions/init<CR>", desc = "open init" },
    { "<leader>?", "<cmd>lua require('fzf-lua').lines({fzf_cli_args = '--with-nth 2..'})<CR>", desc = "lines" },
    { "<leader>h", "<cmd>lua require('fzf-lua').help_tags()<CR>", desc = "help" },
    { "<leader>s", "<cmd>lua require('utils.core').save_session()<CR>", desc = "save session" },
    { "<leader>w", ":w<CR>", desc = "save" },
    { "<leader>z", "<cmd>lua require('fzf-lua').builtin()<CR>", desc = "fzf builtins" },

    { "<leader>c", group = "change dir" },
    { "<leader>cc", ":cd %:p:h<CR>", desc = "change dir cwd" },
    { "<leader>cd", "<cmd>lua require('fzf-lua').fzf_exec([[(echo '..' ; echo '-' ; echo '~' ; find . -type d ! -path \"*.git*\" -follow 2>/dev/null)]], {prompt = 'Cd> ', previewer = false, actions = {['default'] = function(selected) vim.api.nvim_command('cd ' .. selected[1]) end}})<CR>", desc = "change dir" },
    { "<leader>cp", "<cmd>lua require('fzf-lua').fzf_exec([[(echo '..' ; echo '-' ; echo '~' ; find ~/.local -maxdepth 2 -type d ! -path \"*.git*\" -follow 2>/dev/null)]], {prompt = 'Cd> ', previewer = false, actions = {['default'] = function(selected) vim.api.nvim_command('cd ' .. selected[1]) end}})<CR>", desc = "personal projects" },
        -- use if switch to fd over find:
        -- { "<leader>cd", "<cmd>lua require('fzf-lua').fzf_exec([[(echo '..' ; echo '-' ; echo '~' ; fd --type=d --follow --hidden --exclude=.git 2>/dev/null)]], {prompt = 'Cd> ', previewer = false, actions = {['default'] = function(selected) vim.api.nvim_command('cd ' .. selected[1]) end}})<CR>", desc = "change dir" },

    { "<leader>f", group = "fzf find" },
    { "<leader>fc", "<cmd>lua require('fzf-lua').treesitter({query = '[type] '})<CR>", desc = "classes (treesitter)" },
    { "<leader>ff", "<cmd>lua require('fzf-lua').treesitter({query = '[function] '})<CR>", desc = "functions (treesitter)" },

    { "<leader>g", group = "git" },
    { "<leader>ga", "<cmd>lua require('FTerm').scratch({cmd = {'git', 'add', '-i'}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "stage interactively" },
    { "<leader>gb", "<cmd>Gitsigns blame<CR>", desc = "blame" },
    { "<leader>gc", ":cd %:p:h<CR><cmd>lua require('FTerm').scratch({cmd = {'git', 'commit'}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "commit" },
    { "<leader>gd", "<cmd>Gitsigns diffthis<CR>", desc = "diff" },
    { "<leader>gg", "<cmd>lua require('fzf-lua').git_status()<CR>", desc = "status" },
    { "<leader>gi", "<cmd>lua require('gitsigns').blame_line{full=true}<CR>", desc = "blame inline" },
    { "<leader>gj", "<cmd>lua require('gitsigns').nav_hunk('next')<CR>", desc = "next hunk" },
    { "<leader>gk", "<cmd>lua require('gitsigns').nav_hunk('prev')<CR>", desc = "prev hunk" },
    { "<leader>gl", "<cmd>lua require('fzf-lua').git_bcommits({cmd = [[git log --color=always --pretty=format:%C\\(auto\\)%h\\ %s\\ %C\\(green\\)%cs\\ %an]], actions = {['default'] = function(selected) git_show_diff(selected) end}, winopts = {preview = {hidden = 'hidden'}}})<CR>", desc = "log" },
    { "<leader>gp", "<cmd>Gitsigns preview_hunk_inline<CR>", desc = "preview hunk" },
    { "<leader>gr", "<cmd>lua require('FTerm').scratch({cmd = {'git', 'reset', '-p'}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "unstage" },
    { "<leader>gs", "<cmd>Gitsigns stage_hunk<CR>", desc = "stage hunk" },
    { "<leader>gt", "<cmd>lua require('fzf-lua').git_stash()<CR>", desc = "stash list" },
    { "<leader>gu", "<cmd>Gitsigns reset_hunk<CR>", desc = "undo hunk" },

    { "<leader>i", group = "insert text" },
    { "<leader>ib", ":lua require('utils.python').abbrev('sbreak')<CR>", desc = "break" },
    { "<leader>il", ":lua require('utils.python').abbrev('lbreak')<CR>", desc = "long break" },
    { "<leader>ip", ":lua require('utils.python').abbrev('pdb')<CR>", desc = "pdb" },
    { "<leader>it", ":lua require('utils.python').abbrev('this')<CR>", desc = "test this" },

    { "<leader>l", group = "lsp" },
    { "<leader>lc", "<cmd>lua vim.lsp.buf.code_action()<CR>", desc = "code actions" },
    { "<leader>ld", "<cmd>lua require('fzf-lua').lsp_definitions({jump1 = true})<CR>", desc = "definition" },
    { "<leader>lf", "<cmd>lua require('utils.python').darker()<CR>", desc = "apply darker" },
    { "<leader>lh", "<cmd>lua vim.lsp.buf.hover()<CR>", desc = "hover" },
    { "<leader>li", "<cmd>LspInfo<CR>", desc = "info" },
    { "<leader>lI", "<cmd>LspInstallMissing<CR>", desc = "install missing" },
    { "<leader>ll", "<cmd>lua require('fzf-lua').lsp_document_diagnostics()<CR>", desc = "list diagnostics" },
    { "<leader>lm", "<cmd>Mason<CR>", desc = "mason" },
    { "<leader>ln", "<cmd>lua vim.lsp.buf.rename()<CR>", desc = "rename" },
    { "<leader>lr", "<cmd>lua require('fzf-lua').lsp_references()<CR>", desc = "references" },
    { "<leader>lR", "<cmd>LspRestart<CR>", desc = "restart" },
    { "<leader>ls", "<cmd>lua vim.diagnostic.open_float()<CR>", desc = "show line diagnostics" },
    { "<leader>lv", "<cmd>CheckDevEnv<CR>", desc = "verify env" },

    { "<leader>o", group = "open" },
    { "<leader>of", "<cmd>lua require('fzf-lua').files({cwd_prompt = false, prompt = 'Files> ', git_icons = false})<CR>", desc = "files" },
    { "<leader>oh", "<cmd>lua require('fzf-lua').oldfiles()<CR>", desc = "history" },
    { "<leader>os", "<cmd>lua require('fzf-lua').fzf_exec('find ~/.local/share/nvim/sessions -type f ! -path \"*.git*\"', {prompt = 'Sessions> ', previewer = false, actions = {['default'] = function(selected) vim.api.nvim_command('source ' .. selected[1]) end}})<CR>", desc = "session" },
    { "<leader>ot", "<cmd>lua require('FTerm').open()<CR>", desc = "terminal" },

    { "<leader>p", group = "pytest" },
    { "<leader>pb", "<cmd>lua require('FTerm').scratch({cmd = {'pytest', '-sv', '--disable-pytest-warnings', '--cov', require('utils.python').get_pytest_cov_cmd(), '--cov-branch', vim.fn.expand('%:p'), '--cov-report', 'term-missing'}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "branch coverage" },
    { "<leader>pc", "<cmd>lua require('FTerm').scratch({cmd = {'pytest', '-sv', '--disable-pytest-warnings', '--cov', require('utils.python').get_pytest_cov_cmd(), vim.fn.expand('%:p'), '--cov-report', 'term-missing'}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "file coverage" },
    { "<leader>pf", "<cmd>lua require('FTerm').scratch({cmd = {'nosetests', '-sv', '--nologcapture', '--with-id', vim.fn.expand('%:p')}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "(nose) file" },
    { "<leader>pl", "<cmd>lua require('FTerm').scratch({cmd = {'pytest', '-sv', '--disable-pytest-warnings', require('utils.python').get_last_test_name()}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "last-run test" },
    { "<leader>pt", "<cmd>lua require('FTerm').scratch({cmd = {'pytest', '-sv', '--disable-pytest-warnings', '-m', 'this', vim.fn.expand('%:p')}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "these" },
    { "<leader>px", "<cmd>lua require('FTerm').scratch({cmd = {'pytest', '-sv', '--disable-pytest-warnings', '--pdb', '-x', vim.fn.expand('%:p')}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "stop at failure" },
    { "<leader>py", "<cmd>lua require('FTerm').scratch({cmd = {'pytest', '-sv', '--disable-pytest-warnings', vim.fn.expand('%:p')}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "file" },
    { "<leader>pz", "<cmd>lua require('FTerm').scratch({cmd = {'pytest', '-sv', '--disable-pytest-warnings', require('utils.python').get_pytest_single_test_arg()}, hl = 'Normal,FloatBorder:FzfLuaBorder', border = 'rounded'})<CR>", desc = "under cursor" },

    { "<leader>r", group = "ripgrep" },
    { "<leader>rg", "<cmd>lua require('fzf-lua').live_grep({git_icons = false})<CR>", desc = "rg" },
    { "<leader>rl", "<cmd>lua require('fzf-lua').grep({resume=true})<CR>", desc = "rg last" },
    { "<leader>rr", "<cmd>lua require('fzf-lua').grep_cword({multiline = 2})<CR>", desc = "rg word under cursor" },

    { "<leader>t", group = "toggles" },
    { "<leader>td", "<cmd>lua require('utils.core').toggle_diagnostics()<CR>", desc = "diagnostics" },
    { "<leader>th", "<cmd>lua require('utils.core').toggle_inlay_hints()<CR>", desc = "inlay hints" },
    { "<leader>ti", ":IBLToggle<CR>", desc = "indents" },
    { "<leader>tw", "<cmd>lua require('utils.core').toggle_text_wrap()<CR>", desc = "text wrap" },

    { "<leader>x", group = "system" },
    { "<leader>xl", "<cmd>Lazy<CR>", desc = "lazy" },
    { "<leader>xh", "<cmd>checkhealth<CR>", desc = "health" },

    {
        mode = { "v" },
        { "<leader>g", group = "git" },
        { "<leader>gs", ":Gitsigns stage_hunk<CR><esc>", desc = "stage selection" },
        { "<leader>gu", ":Gitsigns undo_stage_hunk<CR><esc>", desc = "undo stage selection" },
    },
})
